[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "muru_documentation"
authors = [{name = "octavioaguila", email = "oeaguila@uc.cl"}]
dynamic = ["version", "description"]
